const PRODUCT_ID = "2fffa400-b132-11f1-b958-cd4bca857c9f";
const SESSION_DAYS = 30;
const OTP_MINUTES = 10;

const const HTML = {
  login: `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sua Renda no Digital</title><style>
body{margin:0;background:#f5f1e8;color:#111;font-family:Arial,sans-serif}.wrap{max-width:520px;margin:0 auto;padding:48px 22px}.box{border:1px solid #cfc9bd;background:#f9f7f2;padding:28px;border-radius:18px}h1{font-size:30px;margin:0 0 10px}p{line-height:1.55;color:#444}input{width:100%;box-sizing:border-box;padding:15px;border:1px solid #aaa;border-radius:10px;background:#fff;font-size:16px;margin:8px 0 12px}button{width:100%;padding:15px;border:0;border-radius:10px;background:#111;color:#fff;font-weight:700;font-size:16px}small{display:block;margin-top:14px;color:#777}</style></head><body><main class="wrap"><div class="box"><div style="font-size:13px;font-weight:700;letter-spacing:.08em">SUA RENDA NO DIGITAL</div><h1>Area do aluno</h1><p>Digite o mesmo e-mail usado na compra. Enviaremos um codigo de acesso.</p><form method="post" action="/login"><input name="email" type="email" autocomplete="email" placeholder="seu@email.com" required><button>ENVIAR CODIGO</button></form><small>O acesso e liberado somente para compras aprovadas.</small></div></main></body></html>`,

  otp: (email) => `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Confirmar acesso</title><style>body{margin:0;background:#f5f1e8;color:#111;font-family:Arial,sans-serif}.wrap{max-width:520px;margin:0 auto;padding:48px 22px}.box{border:1px solid #cfc9bd;background:#f9f7f2;padding:28px;border-radius:18px}h1{font-size:28px}input{width:100%;box-sizing:border-box;padding:15px;border:1px solid #aaa;border-radius:10px;font-size:20px;letter-spacing:.3em;text-align:center}button{width:100%;margin-top:12px;padding:15px;border:0;border-radius:10px;background:#111;color:#fff;font-weight:700}</style></head><body><main class="wrap"><div class="box"><h1>Digite o codigo</h1><p>Enviamos um codigo de 6 digitos para <b>${escapeHtml(email)}</b>.</p><form method="post" action="/verify"><input name="email" type="hidden" value="${escapeAttr(email)}"><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required><button>ENTRAR</button></form></div></main></body></html>`,

  app: `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sua Renda no Digital</title><style>body{margin:0;background:#f5f1e8;color:#111;font-family:Arial,sans-serif}.wrap{max-width:720px;margin:0 auto;padding:40px 20px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.12em}h1{font-size:38px;line-height:1.05;margin:12px 0}p{line-height:1.6;color:#444}.card{background:#f9f7f2;border:1px solid #cfc9bd;border-radius:18px;padding:22px;margin:18px 0}.item{padding:17px 0;border-top:1px solid #111}.item:first-child{border-top:0}.num{font-size:12px;color:#777}a{color:#111;font-weight:700}form{margin-top:24px}button{padding:12px 18px;border:1px solid #111;background:#111;color:#fff;border-radius:9px}</style></head><body><main class="wrap"><div class="eyebrow">SUA RENDA NO DIGITAL</div><h1>Seu ponto de partida.</h1><p>Conteudo pratico para comecar a entender caminhos de venda pela internet sem ficar perdido com tanta informacao.</p><div class="card"><h2>O que voce vai encontrar</h2><div class="item"><span class="num">01</span><br>Vendendo produtos</div><div class="item"><span class="num">02</span><br>Prestando servicos</div><div class="item"><span class="num">03</span><br>Encontrando clientes</div><div class="item"><span class="num">04</span><br>Indicacoes & parcerias</div><div class="item"><span class="num">05</span><br>Vendendo pelo WhatsApp</div><div class="item"><span class="num">06</span><br>Criando sua oferta</div><div class="item"><span class="num">07</span><br>Primeiro teste</div></div><form method="post" action="/logout"><button>SAIR</button></form></main></body></html>`
};
